### PR TITLE
Ranges, example tests and benchmarks

### PR DESCRIPTION
**Pull request by dtkaczyk**
This change is [Reviewable](https://reviewable.io/reviews/zagrodzki/goscope/11)

### CODE REVIEW

**Comment by zagrodzki** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[gui/gui.go, line 44 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDj1OdrsrhF1dCMlsl:-KTDj1OdrsrhF1dCMlsm:b-jhd4vq) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/gui/gui.go#L44)):_

> ``` Go
> // ChannelYRange represents a y-range of samples to be plotted
> type ChannelYRange struct {
>   Min float64
> ```

It might be better to use Zero and Scale? Or some such, I can't think of a good name. As in, the vertical position of zero value on the graph (0..1) and vertical scale in some units (volts per screen height?).
A traditional scope would use volts/div and the screen would have a fixed number of divs marked on it (typically with actual paint, so it wasn't configurable...).  Volts per screen height would be similar and trivially converted to V/div.

It's ok for a trace to go beyond the screen boundaries.

---

_[gui/gui_test.go, line 15 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDnLgOpkY94zHmr5sO:-KTDnLgOpkY94zHmr5sP:bsfucma) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/gui/gui_test.go#L15)):_

> ``` Go
> //  limitations under the License.
> 
> package gui
> ```

Add tests for the internal methods as well, i.e. unit tests - tests for CreatePlot/Png are more of an integration test, they are not great for testing corner cases of individual pieces.

---

_[gui/gui_test.go, line 29 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDm4uIHEH1m8RljVQM:-KTDm4uIHEH1m8RljVQN:bm64tnt) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/gui/gui_test.go#L29)):_

> ``` Go
>       t.Fatalf("Cannot open the device: %v", err)
>   }
>   err = PlotToPng(dev, make(map[scope.ChanID]ChannelYRange), "plot1.png")
> ```

I think there is some way to use a temp directory created specially for the test, let me look it up...

---

_[gui/gui_test.go, line 35 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDmWxvUZCGihI0KkXD:-KTDmWxwdCQyz8tRzda-:b-qw3xcx) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/gui/gui_test.go#L35)):_

> ``` Go
> }
> 
> func TestPlotToPngWithRanges(t *testing.T) {
> ```

I think it would be better to test CreatePlot instead of PlotToPng. It gives you a more useful result - an Plot/Image, that you could compare to a golden image stored in a file. That way you could test how the Image looks like, not only that it doesn't return an error.

---

_[misc/benchmarks/plot_test.go, line 15 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDnnr8FSK7S7t0a_fu:-KTDnnr8FSK7S7t0a_fv:b-jtdb8m) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/misc/benchmarks/plot_test.go#L15)):_

> ``` Go
> //  limitations under the License.
> 
> package benchmark
> ```

Move these benchmarks to the gui_test. It's common to keep benchmarks and tests together. The benchmarks directory was created only because the benchmarks that I put there are not tied to a particular piece of goscope code.

---

_[misc/benchmarks/plot_test.go, line 25 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDoZKlXgmzgNTnan-q:-KTDoZKlXgmzgNTnan-r:bj6zky9) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/misc/benchmarks/plot_test.go#L25)):_

> ``` Go
> )
> 
> func BenchmarkGuiFull(b *testing.B) {
> ```

Not sure if this benchmark is necessary - you're effectively testing your disk speed and/or standard library encoder. Considering that in the final GUI you won't use PNG often, I think it's ok to not benchmark file encoding.

---

_[misc/benchmarks/plot_test.go, line 43 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDoIC-3gEVGj0ALJ65:-KTDoIC-3gEVGj0ALJ66:b-vqrtpa) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/misc/benchmarks/plot_test.go#L43)):_

> ``` Go
>       if err != nil {
>           b.Fatalf("Cannot open the device: %v", err)
>       }
> ```

Perhaps call b.ResetTimer after dummy.Open, to exclude it's time from the benchmark time. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/11)_

**Comment by dtkaczyk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

_[gui/gui.go, line 44 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDj1OdrsrhF1dCMlsl:-KTYqMG3ej_FR4iMPnMc:b-zbudlk) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/gui/gui.go#L44)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> It might be better to use Zero and Scale? Or some such, I can't think of a good name. As in, the vertical position of zero value on the graph (0..1) and vertical scale in some units (volts per screen height?).
> A traditional scope would use volts/div and the screen would have a fixed number of divs marked on it (typically with actual paint, so it wasn't configurable...).  Volts per screen height would be similar and trivially converted to V/div.
> 
> It's ok for a trace to go beyond the screen boundaries.
> </details>
> I changed SampleYRange to something like this.

---

_[gui/gui_test.go, line 15 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDnLgOpkY94zHmr5sO:-KTYqWa06jOCLcEbe1W-:bzf43m7) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/gui/gui_test.go#L15)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> Add tests for the internal methods as well, i.e. unit tests - tests for CreatePlot/Png are more of an integration test, they are not great for testing corner cases of individual pieces.
> </details>
> This will take some time, I'd like to do this in a separate pull request.

---

_[gui/gui_test.go, line 29 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDm4uIHEH1m8RljVQM:-KTYsQ51mNgFDXWtBTF6:b-abin3d) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/gui/gui_test.go#L29)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> I think there is some way to use a temp directory created specially for the test, let me look it up...
> </details>
> I guess I could use os.TempDir() and put the resulting plots there. Is there a better way?

---

_[gui/gui_test.go, line 35 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDmWxvUZCGihI0KkXD:-KTYu2cCdQm96jZuqQ-x:b-3xpmuj) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/gui/gui_test.go#L35)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> I think it would be better to test CreatePlot instead of PlotToPng. It gives you a more useful result - an Plot/Image, that you could compare to a golden image stored in a file. That way you could test how the Image looks like, not only that it doesn't return an error.
> </details>
> Sure, but how do I create this golden image? I am not sure how to generate the image as it should look like, especially since the plotting algorithm is not stable yet.

Right now the "tests" contain what was in the main() before, and you can at least judge the result with your eyes.

---

_[misc/benchmarks/plot_test.go, line 15 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDnnr8FSK7S7t0a_fu:-KTYwA7wONkx-BFRaMDR:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/misc/benchmarks/plot_test.go#L15)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> Move these benchmarks to the gui_test. It's common to keep benchmarks and tests together. The benchmarks directory was created only because the benchmarks that I put there are not tied to a particular piece of goscope code.
> </details>
> Done.

---

_[misc/benchmarks/plot_test.go, line 25 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDoZKlXgmzgNTnan-q:-KTYwE3kJ36nDzmVy7Ck:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/misc/benchmarks/plot_test.go#L25)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> Not sure if this benchmark is necessary - you're effectively testing your disk speed and/or standard library encoder. Considering that in the final GUI you won't use PNG often, I think it's ok to not benchmark file encoding.
> </details>
> Done.

---

_[misc/benchmarks/plot_test.go, line 43 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDoIC-3gEVGj0ALJ65:-KTYwCb2AiltPQbWcRcm:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/misc/benchmarks/plot_test.go#L43)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> Perhaps call b.ResetTimer after dummy.Open, to exclude it's time from the benchmark time. 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/11)_

**Comment by zagrodzki** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[gui/gui_test.go, line 29 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDm4uIHEH1m8RljVQM:-KTYwASDvmtf-iZdN1NG:bpthxh8) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/gui/gui_test.go#L29)):_
<details><summary>

<i>Previously, dtkaczyk (Dominika Tkaczyk) wrote…</i></summary>



> I guess I could use os.TempDir() and put the resulting plots there. Is there a better way?
> </details>
> it seems ioutil.TempDir() does a little more - it creates a new dedicated directory under os.TempDir(). And os.RemoveAll() can be used to clean it up. Snippet: https://play.golang.org/p/qGmfB_M91t

---

_[gui/gui_test.go, line 35 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDmWxvUZCGihI0KkXD:-KTYwneTK8Si_IlIFXfC:b-y4kvrs) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/gui/gui_test.go#L35)):_
<details><summary>

<i>Previously, dtkaczyk (Dominika Tkaczyk) wrote…</i></summary>



> Sure, but how do I create this golden image? I am not sure how to generate the image as it should look like, especially since the plotting algorithm is not stable yet.
> 
> Right now the "tests" contain what was in the main() before, and you can at least judge the result with your eyes.
> </details>
> I would probably use Gimp or something similar to write a PNG file that you could submit next to the code. The test would take the golden filename, load a PNG from the file as image.Image, then compare the two images.
> I don't think we need to do it all at once though. And we can start with something super simple, e.g. plotting dummy "zero" channel on a small (e.g. 80x60) image.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/11)_

**Comment by zagrodzki** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[gui/gui_test.go, line 35 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/11#-KTDmWxvUZCGihI0KkXD:-KTZOUL-Bcs5BkYWmrdi:b-5utqfw) ([raw file](https://github.com/zagrodzki/goscope/blob/2c60863d9d1196b1a24821d2a37982be02035bc9/gui/gui_test.go#L35)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> I would probably use Gimp or something similar to write a PNG file that you could submit next to the code. The test would take the golden filename, load a PNG from the file as image.Image, then compare the two images.
> I don't think we need to do it all at once though. And we can start with something super simple, e.g. plotting dummy "zero" channel on a small (e.g. 80x60) image.
> </details>
> (add a TODO: compare the resulting image somehow)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/11)_

**Pull request merged**
