### PR TITLE
Use the endpoint read stream interface, introduced in gousb 2.0.

### PR DESCRIPTION
**Pull request by zagrodzki**
This change is [Reviewable](https://reviewable.io/reviews/zagrodzki/goscope/41)

### CODE REVIEW

**Comment by zagrodzki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/zagrodzki/goscope/41#-KsjXQmTPqZOyMUy0d6M:-KsjXQmTPqZOyMUy0d6N:borvbyx) (no related file):*
@dtkaczyk miau?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/41)*

**Comment by dtkaczyk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[usb/hantek6022be/capture.go, line 51 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/41#-KtDiU6pDbJDhCJg0vOv:-KtDiU6qiVgWkMPrfVIp:bupe9kj) ([raw file](https://github.com/zagrodzki/goscope/blob/1db570f2a6e7bb3c6ea7db613684393bf9482074/usb/hantek6022be/capture.go#L51)):*
> ```Go
> }
> 
> var sampleBuf = make([]byte, 3072*10)
> ```

Please add a comment about the number.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/41)*

**Comment by zagrodzki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[usb/hantek6022be/capture.go, line 51 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/41#-KtDiU6pDbJDhCJg0vOv:-KtDmzmv_5rG-I5KW2mw:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/1db570f2a6e7bb3c6ea7db613684393bf9482074/usb/hantek6022be/capture.go#L51)):*
<details><summary><i>Previously, dtkaczyk (Dominika Tkaczyk) wrote…</i></summary><blockquote>

Please add a comment about the number.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/41)*

**Comment by dtkaczyk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/41)*

**Pull request merged**
