### PR TITLE
Initial code integrated and corrected

### PR DESCRIPTION
**Pull request by dtkaczyk**
This change is [Reviewable](https://reviewable.io/reviews/zagrodzki/goscope/8)

### CODE REVIEW

**Comment by zagrodzki** [comment]
run gofmt -w gui/gui.go to fix formatting.
run golint to see the style errors. They don't fail unittests currently, but you can see them here:
https://circleci.com/gh/zagrodzki/goscope/65
(expand the "golint" section)

**Comment by zagrodzki** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_[gui/gui.go, line 16 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScR4ULD1e1ix_tJuq7:-KScR4ULD1e1ix_tJuq8:b-bk5csx) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L16)):_

> ``` Go
> 
> 
> type AggrPoint struct {
> ```

assuming this will at some point become a package, if the AggrPoint is an internal structure that would not be exposed to package users, you would name it "aggrPoint" to avoid exporting.

If AggrPoint is useful outside of the package, then X, SumX and SizeX should be capitalized. Otherwise, package users can create the AggrPoint{} literal, but can't assign it's fields.
It's worth noting that private fields would be fine if you have an externally visible constructor-like function (e.g. NewAggrPoint) that wil initialize the value and some public methods to operate on the struct.

---

_[gui/gui.go, line 22 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScTmLpwC8kt3mpXxzA:-KScTmLpwC8kt3mpXxzB:bhspupa) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L22)):_

> ``` Go
> }
> 
> func (p AggrPoint) add(x, y int) AggrPoint {
> ```

It might be better to use a pointer receiver and modify aggrPoint in place:

func (p *AggrPoint) add(x, y int) {
  p.x = x
  p.sumY += y
  p.sizeY++
}

x is repeated in the aggrPoints map key and in the aggrPoint itself, perhaps you can omit X in aggrPoint entirely and instead make it a param of toPoint method?

---

_[gui/gui.go, line 52 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScV8YaL971PDC1ke2P:-KScV8YaL971PDC1ke2Q:b-5azapi) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L52)):_

> ``` Go
>     aggrPoints := make(map[int]AggrPoint)
>     for i, y := range s {
>         mapX := int(float64(start.X) + float64(i) / rangeX * float64(end.X - start.X))
> ```

perhaps pull end.X - start.X and end.Y - start.Y as a separate variable before the for loop, so that it doesn't have to be calculated on every turn.  Perhaps the same for float64(start.X) and float64(end.Y)

---

_[gui/gui.go, line 56 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScWxqNsC22w0J-PEQ8:-KScWxqNsC22w0J-PEQ9:b-14tmq5) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L56)):_

> ``` Go
>         aggrPoints[mapX] = aggrPoints[mapX].add(mapX, mapY)
>     }
>     fmt.Println(aggrPoints)
> ```

left from debugging?

---

_[gui/gui.go, line 85 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScZd8lVa3Dekkz5okz:-KScZd8meOPnn-RCuN0C:b-pwmjie) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L85)):_

> ``` Go
>         return
>     }
>     a := float64(p1.Y - p2.Y) / float64(p1.X - p2.X)
> ```

perhaps call it "ratio"

---

_[gui/gui.go, line 86 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScZwBOmKYqRdPTz7tW:-KScZwBOmKYqRdPTz7tX:b-coglj) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L86)):_

> ``` Go
>     }
>     a := float64(p1.Y - p2.Y) / float64(p1.X - p2.X)
>     b := float64(p1.Y) - float64(p1.X) * a
> ```

what is b? I'm pretty sure it works, but I don't understand the calculation.

---

_[gui/gui.go, line 122 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KSc_ZlOQdjU9jrZxyHs:-KSc_ZlOQdjU9jrZxyHt:bp9x839) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L122)):_

> ``` Go
> 
> 
> type XSorter []image.Point
> ```

internal type, xSorter. Or perhaps pointsByX or something like that?

---

_[gui/gui.go, line 160 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KSc_ptuMLGFoVlf6SQr:-KSc_ptuMLGFoVlf6SQs:b-2v7vle) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L160)):_

> ``` Go
> 
> func main() {
>     dum, _ := dummy.Open("")
> ```

putting non-trivial code in main() makes it difficult to write tests.
Separate into plot(dev scope.Device, outputFile string) error
and in main, just initialize device, call plot(device, output) and fail if error.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/8)_

**Comment by dtkaczyk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_[gui/gui.go, line 16 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScR4ULD1e1ix_tJuq7:-KSmdoOxZRgd7w04B34U:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L16)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> assuming this will at some point become a package, if the AggrPoint is an internal structure that would not be exposed to package users, you would name it "aggrPoint" to avoid exporting.
> 
> If AggrPoint is useful outside of the package, then X, SumX and SizeX should be capitalized. Otherwise, package users can create the AggrPoint{} literal, but can't assign it's fields.
> It's worth noting that private fields would be fine if you have an externally visible constructor-like function (e.g. NewAggrPoint) that wil initialize the value and some public methods to operate on the struct.
> </details>
> Done.

---

_[gui/gui.go, line 22 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScTmLpwC8kt3mpXxzA:-KSmeCIicaqxFZ7XAyIq:bd5t736) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L22)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> It might be better to use a pointer receiver and modify aggrPoint in place:
> 
> func (p *AggrPoint) add(x, y int) {
>   p.x = x
>   p.sumY += y
>   p.sizeY++
> }
> 
> x is repeated in the aggrPoints map key and in the aggrPoint itself, perhaps you can omit X in aggrPoint entirely and instead make it a param of toPoint method?
> </details>
> This was one of the first thing I've tried. However, this produces the following error: "cannot take the address of aggrPoints[mapX]". I read this is because it's not allowed to use the address of a map entry, since it can change during map growing or shrinking. I am not sure whether and how it can be fixed.

It seems somehow nicer to me that aggrPoint is "self-contained" by keeping x inside. This way I can store it in a map or an array, or anything else, and all needed information will be preserved. Bu I agree right now it's redundant, and aggrPoint is private anyway, so if you insist, I will correct this.

---

_[gui/gui.go, line 52 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScV8YaL971PDC1ke2P:-KSmds5j40TgLbC8UoNq:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L52)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> perhaps pull end.X - start.X and end.Y - start.Y as a separate variable before the for loop, so that it doesn't have to be calculated on every turn.  Perhaps the same for float64(start.X) and float64(end.Y)
> </details>
> Done.

---

_[gui/gui.go, line 56 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScWxqNsC22w0J-PEQ8:-KSme-_qUaAaCWffNh7o:bss4a2b) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L56)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> left from debugging?
> </details>
> Removed.

---

_[gui/gui.go, line 85 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScZd8lVa3Dekkz5okz:-KSme2a3gxukQUCQ-EVe:by7pmph) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L85)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> perhaps call it "ratio"
> </details>
> I added some comments to clarify.

---

_[gui/gui.go, line 86 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScZwBOmKYqRdPTz7tW:-KSme5xc-PuzDZSnzOn5:by7pmph) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L86)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> what is b? I'm pretty sure it works, but I don't understand the calculation.
> </details>
> I added some comments to clarify.

---

_[gui/gui.go, line 122 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KSc_ZlOQdjU9jrZxyHs:-KSme8Itj7HUDf0WlfeW:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L122)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> internal type, xSorter. Or perhaps pointsByX or something like that?
> </details>
> Done.

---

_[gui/gui.go, line 160 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KSc_ptuMLGFoVlf6SQr:-KSme9QftH1vDj-W49fo:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L160)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> putting non-trivial code in main() makes it difficult to write tests.
> Separate into plot(dev scope.Device, outputFile string) error
> and in main, just initialize device, call plot(device, output) and fail if error.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/8)_

**Comment by zagrodzki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

_[gui/gui.go, line 22 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScTmLpwC8kt3mpXxzA:-KSmksxfxOawOv0F-oyo:b-o1933) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L22)):_
<details><summary>

<i>Previously, dtkaczyk (Dominika Tkaczyk) wrote…</i></summary>



> This was one of the first thing I've tried. However, this produces the following error: "cannot take the address of aggrPoints[mapX]". I read this is because it's not allowed to use the address of a map entry, since it can change during map growing or shrinking. I am not sure whether and how it can be fixed.
> 
> It seems somehow nicer to me that aggrPoint is "self-contained" by keeping x inside. This way I can store it in a map or an array, or anything else, and all needed information will be preserved. Bu I agree right now it's redundant, and aggrPoint is private anyway, so if you insist, I will correct this.
> </details>
> I see. You could use the map of pointers:
> map[int]*aggrPoint
> but that loses the convenience of using zero-element for .add(). OTOH, perhaps a nil check is not much more complex:

if aggrPoints[x] == nil {
  aggrPoints[x] = new(aggrPoint)
}
agrrPoints[x].add(...)

or alternatively, if you want to keep the overwrite pattern:

func (p *aggrPoint) add(int y) *aggrPoint {
  if p == nil {
    return &aggrPoint{y, 1}
  }
  p.sum += y
  p.size++
  return p
}

It then behaves sort of like append, but I'm not sure I like this pattern better.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/8)_

**Comment by zagrodzki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

_[gui/gui.go, line 85 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KScZd8lVa3Dekkz5okz:-KSmoKxLYrZT-8EPyq2x:b-vpfqzu) ([raw file](https://github.com/zagrodzki/goscope/blob/553ab80b5d21c83e454308171ad775e0f5290bec/gui/gui.go#L85)):_
<details><summary>

<i>Previously, dtkaczyk (Dominika Tkaczyk) wrote…</i></summary>



> I added some comments to clarify.
> </details>
> LGTM. Now it's clear :)

---

_[gui/gui.go, line 149 at r3](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KSmp8K-00AFwk_o1vHL:-KSmp8K-00AFwk_o1vHM:bl2iis7) ([raw file](https://github.com/zagrodzki/goscope/blob/155121cafa4b156a1192e0f946fdf25ef72fbc1c/gui/gui.go#L149)):_

> ``` Go
>   }
>   samples := (<-data).Samples
>   defer stop()
> ```

move stop() just after the resource is "acquired"/opened, i.e. just below StartSampling().

---

_[gui/gui.go, line 215 at r3](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KSmpLOgj1q-SrY1sSWZ:-KSmpLOhB-ihLtd_0SFO:b4jnm8b) ([raw file](https://github.com/zagrodzki/goscope/blob/155121cafa4b156a1192e0f946fdf25ef72fbc1c/gui/gui.go#L215)):_

> ``` Go
>   dev, err := dummy.Open("")
>   if err != nil {
>       panic(err)
> ```

FYI, it might be nicer to use log.Fatalf() instead. It won't dump the entire stack trace to stderr, just the error. But the effect will be the same (crash and return non-0).

---

_[gui/gui.go, line 218 at r3](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KSmpgVgZA44HhXcFR1S:-KSmpgVgZA44HhXcFR1T:bov1lic) ([raw file](https://github.com/zagrodzki/goscope/blob/155121cafa4b156a1192e0f946fdf25ef72fbc1c/gui/gui.go#L218)):_

> ``` Go
>   }
>   if plot(dev, "draw.png") != nil {
>       panic(err)
> ```

this err is nil, because it's still the same erro from dummy.Open. if err := plot(..); err != nil { ...

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/8)_

**Comment by zagrodzki** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/8)_

**Comment by zagrodzki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

_[gui/gui.go, line 215 at r4](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-KSmvuXDTqwmIWydQ-Ry:-KSmvuXDTqwmIWydQ-Rz:bypjsct) ([raw file](https://github.com/zagrodzki/goscope/blob/baeca8ecda5365a2e10948cdce61271cffa49fc0/gui/gui.go#L215)):_

> ``` Go
>   dev, err := dummy.Open("")
>   if err != nil {
>       log.Fatalf("Cannot open the device", err)
> ```

Fatalf is like Printf, takes formatting arguments. So you need log.Fatalf("Cannot open the device: %v", err)
Same below.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/8)_

**Comment by zagrodzki** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/8)_

**Comment by zagrodzki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-:-KSmxt-wJl7FwOnpAJSC:bnfp4nl)_

**Comment by zagrodzki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/8#-:-KSmyJByolfwK7eg8igI:bnfp4nl)_

**Review by zagrodzki — APPROVED** [review]
LGTM

**Pull request merged**
