### PR TITLE
Custom firmware update

### PR DESCRIPTION
**Pull request by zagrodzki**
Replace the firmware with a HEAD version from https://github.com/rpcope1/Hantek6022API/commits/master/PyHT6022/HantekFirmware/custom.
It incorporates AADJ changes from https://github.com/rpcope1/Hantek6022API/pull/37 and subsequent fix in https://github.com/rpcope1/Hantek6022API/commit/b5c76772e47a4fc47711ebebb89de3bb71f7bd80

---
This change is [Reviewable](https://reviewable.io/reviews/zagrodzki/goscope/38)

### CODE REVIEW

**Comment by dtkaczyk** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[usb/hantek6022be/custom_firmware/device.c, line 4 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/38#-KpoF-mEBipeTBIAtyzv:-KpoF-mEBipeTBIAtyzw:bni0con) ([raw file](https://github.com/zagrodzki/goscope/blob/403d614b27e5907775f75908226e1a57e83c6344/usb/hantek6022be/custom_firmware/device.c#L4)):*
> ```C
>  * Copyright (C) 2009 Ubixum, Inc. 
>  * Copyright (C) 2015 Jochen Hoenicke
>  * Copyright (C) 2017 Sebastian Zagrodzki
> ```

In the README there is a short note that this code was copied from jhoenicke (https://github.com/jhoenicke), but I cannot see the information which files were copied and from where exactly. I would add this.

---

*[usb/hantek6022be/custom_firmware/device.c, line 130 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/38#-KplA9J98Xz7GrJuS9Lk:-KplA9J98Xz7GrJuS9Ll:b-1ntn4u) ([raw file](https://github.com/zagrodzki/goscope/blob/403d614b27e5907775f75908226e1a57e83c6344/usb/hantek6022be/custom_firmware/device.c#L130)):*
> ```C
>     clear_fifo();
> 
>     for (i = 0; i < 1000; i++);
> ```

What is the purpose of this line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/38)*

**Comment by zagrodzki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[usb/hantek6022be/custom_firmware/device.c, line 4 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/38#-KpoF-mEBipeTBIAtyzv:-KpoHLTyy0SwWRjEELg8:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/403d614b27e5907775f75908226e1a57e83c6344/usb/hantek6022be/custom_firmware/device.c#L4)):*
<details><summary><i>Previously, dtkaczyk (Dominika Tkaczyk) wrote…</i></summary><blockquote>

In the README there is a short note that this code was copied from jhoenicke (https://github.com/jhoenicke), but I cannot see the information which files were copied and from where exactly. I would add this.
</blockquote></details>

Done.

---

*[usb/hantek6022be/custom_firmware/device.c, line 130 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/38#-KplA9J98Xz7GrJuS9Lk:-KpoIHnYWzqv1OsJbRgT:bl1l2sq) ([raw file](https://github.com/zagrodzki/goscope/blob/403d614b27e5907775f75908226e1a57e83c6344/usb/hantek6022be/custom_firmware/device.c#L130)):*
<details><summary><i>Previously, dtkaczyk (Dominika Tkaczyk) wrote…</i></summary><blockquote>

What is the purpose of this line?
</blockquote></details>

it's a low-level implementation of time.sleep. The compiler does not optimize this away, and the length of the sleep is equal to 1000 * cycles_per_iteration / clock speed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/38)*

**Comment by dtkaczyk** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[usb/hantek6022be/custom_firmware/device.c, line 130 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/38#-KplA9J98Xz7GrJuS9Lk:-Kq440dou_A3O1Hvwmad:bb7qlj1) ([raw file](https://github.com/zagrodzki/goscope/blob/403d614b27e5907775f75908226e1a57e83c6344/usb/hantek6022be/custom_firmware/device.c#L130)):*
<details><summary><i>Previously, zagrodzki wrote…</i></summary><blockquote>

it's a low-level implementation of time.sleep. The compiler does not optimize this away, and the length of the sleep is equal to 1000 * cycles_per_iteration / clock speed.
</blockquote></details>

Right. What I still don't get is why this and not sleep.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/38)*

**Comment by zagrodzki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[usb/hantek6022be/custom_firmware/device.c, line 130 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/38#-KplA9J98Xz7GrJuS9Lk:-Kq5DOzNGtxuFfD9lsXw:b-djbdr7) ([raw file](https://github.com/zagrodzki/goscope/blob/403d614b27e5907775f75908226e1a57e83c6344/usb/hantek6022be/custom_firmware/device.c#L130)):*
<details><summary><i>Previously, dtkaczyk (Dominika Tkaczyk) wrote…</i></summary><blockquote>

Right. What I still don't get is why this and not sleep.
</blockquote></details>

The primary reason seems to be that sleep does not exist.

In your typical high level programming, the "sleep" command would signal the operating system "this process is now going to wait". The operating system would then register some sort of future event, adjust some memory structures (the "runnable" queue or some such), pick some other process and tell it to continue. Or, if there's nothing else that is runnable, would move to some sort of low power mode, waking up periodically to check if there's anything that is supposed to wake up.

Here the operating system doesn't exist though - the only code that executes is this program, with no scheduling, no notion of processes etc. If it wants to add a delay of certain length, it needs to do it in one of these ways:
* rely on some sort of external event to tell it "you need to continue now". Sometihng like "wait until the voltage on pin foo moves from low to high", or similar. This typically makes sense for a long wait, when you e.g. want to wait until a certain time of day.
* keep looping actively for a number of times, passing time doing nothing. This makes sense for a short delay.

In this case, because the intended wait is very short, it does the latter. I imagine the number is pretty arbitrary and it was just added as "waste some time", presumably to avoid situation where GPIFTRIG is not set _yet_ because of the previous transaction or something.

Out of curiosity, I checked how much time this actually takes. Looking at the assembly listing from compiled code, I see this:

```
;   device.c:130: for (i = 0; i < 1000; i++);                                   
    mov r6,#0xE8                                                                
    mov r7,#0x03                                                                
00110$:                                                                         
    dec r6                                                                      
    cjne    r6,#0xFF,00127$                                                     
    dec r7                                                                      
00127$:                                                                         
    mov a,r6                                                                    
    orl a,r7                                                                    
    jnz 00110$
```

i.e.: set registers r7/r6 to 0x03 (3) and 0xE8 (232). Decrease r6. If r6 is equal 0xff (which would occur after decreasing r6 from 0x00), decrease r7, otherwise skip (jump to label "00127$".) Move contents r6 to register a,  OR them with r7, if the result is non-zero jump to 00110$ - i.e. jump to 00110$ as long as either r6 or r7 are non-zero.

So it keeps decreasing the r6, every time it wraps from 0x00 to 0xff decrease r7. 0x03 * 256 (00..ff) + 0xe8 = 768 + 232 = 1000, so r7 * 256 + r6 = 1000, that's the counter.

The 2 "movs" at the beginning are executed once, and the rest of that snippet is executed a 1000 times, with the exception of "dec r7" which is executed 3 times.

Per 8051 CPU manual (see http://www.keil.com/support/man/docs/is51/is51_instructions.htm): mov is 1 cycle, dec is 1 cycle, cjne is 2 cycles, orl is 1 cycle,  jnz is 2 cycles.

That means the entire loop takes 2 * 1 + 1000 * (1+2+1+1+2) + 3 * 1 = 7005 cycles, at 48MHz that's ~146 microseconds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/38)*

**Comment by zagrodzki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[usb/hantek6022be/custom_firmware/device.c, line 130 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/38#-KplA9J98Xz7GrJuS9Lk:-Kq5ND36rjYhO5DSNV18:b-o1i38o) ([raw file](https://github.com/zagrodzki/goscope/blob/403d614b27e5907775f75908226e1a57e83c6344/usb/hantek6022be/custom_firmware/device.c#L130)):*
<details><summary><i>Previously, zagrodzki wrote…</i></summary><blockquote>

The primary reason seems to be that sleep does not exist.

In your typical high level programming, the "sleep" command would signal the operating system "this process is now going to wait". The operating system would then register some sort of future event, adjust some memory structures (the "runnable" queue or some such), pick some other process and tell it to continue. Or, if there's nothing else that is runnable, would move to some sort of low power mode, waking up periodically to check if there's anything that is supposed to wake up.

Here the operating system doesn't exist though - the only code that executes is this program, with no scheduling, no notion of processes etc. If it wants to add a delay of certain length, it needs to do it in one of these ways:
* rely on some sort of external event to tell it "you need to continue now". Sometihng like "wait until the voltage on pin foo moves from low to high", or similar. This typically makes sense for a long wait, when you e.g. want to wait until a certain time of day.
* keep looping actively for a number of times, passing time doing nothing. This makes sense for a short delay.

In this case, because the intended wait is very short, it does the latter. I imagine the number is pretty arbitrary and it was just added as "waste some time", presumably to avoid situation where GPIFTRIG is not set _yet_ because of the previous transaction or something.

Out of curiosity, I checked how much time this actually takes. Looking at the assembly listing from compiled code, I see this:

```
;   device.c:130: for (i = 0; i < 1000; i++);                                   
    mov r6,#0xE8                                                                
    mov r7,#0x03                                                                
00110$:                                                                         
    dec r6                                                                      
    cjne    r6,#0xFF,00127$                                                     
    dec r7                                                                      
00127$:                                                                         
    mov a,r6                                                                    
    orl a,r7                                                                    
    jnz 00110$
```

i.e.: set registers r7/r6 to 0x03 (3) and 0xE8 (232). Decrease r6. If r6 is equal 0xff (which would occur after decreasing r6 from 0x00), decrease r7, otherwise skip (jump to label "00127$".) Move contents r6 to register a,  OR them with r7, if the result is non-zero jump to 00110$ - i.e. jump to 00110$ as long as either r6 or r7 are non-zero.

So it keeps decreasing the r6, every time it wraps from 0x00 to 0xff decrease r7. 0x03 * 256 (00..ff) + 0xe8 = 768 + 232 = 1000, so r7 * 256 + r6 = 1000, that's the counter.

The 2 "movs" at the beginning are executed once, and the rest of that snippet is executed a 1000 times, with the exception of "dec r7" which is executed 3 times.

Per 8051 CPU manual (see http://www.keil.com/support/man/docs/is51/is51_instructions.htm): mov is 1 cycle, dec is 1 cycle, cjne is 2 cycles, orl is 1 cycle,  jnz is 2 cycles.

That means the entire loop takes 2 * 1 + 1000 * (1+2+1+1+2) + 3 * 1 = 7005 cycles, at 48MHz that's ~146 microseconds.

</blockquote></details>

also looking under the hood in Arduino, I see that the implementation of delayMicroseconds() is something like this:

```
    // busy wait                                                                
    __asm__ __volatile__ (                                                      
        "1: sbiw %0,1" "\n\t" // 2 cycles                                       
        "brne 1b" : "=w" (us) : "0" (us) // 2 cycles                            
    );                                                                          
    // return = 4 cycles                                                        
```

I don't speak that dialect of assembler myself, but you can see from the comments the idea is very similar.

You could wrap it in a function and do a function call:

```
// delay expressed in units of ~6 microseconds
void sleep(int n) {
  for (int i = 0; i < n; i++) { for (char j = 0; j < 255; j++); }
}
```

and use it like this:

```
sleep(20);
```

In this firmware there was probably little benefit to splititng that code out into a separate function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/38)*

**Comment by dtkaczyk** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[usb/hantek6022be/custom_firmware/device.c, line 130 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/38#-KplA9J98Xz7GrJuS9Lk:-Kq7WXERs0I3OubZ0x12:b-sr9xm5) ([raw file](https://github.com/zagrodzki/goscope/blob/403d614b27e5907775f75908226e1a57e83c6344/usb/hantek6022be/custom_firmware/device.c#L130)):*
<details><summary><i>Previously, zagrodzki wrote…</i></summary><blockquote>

also looking under the hood in Arduino, I see that the implementation of delayMicroseconds() is something like this:

```
    // busy wait                                                                
    __asm__ __volatile__ (                                                      
        "1: sbiw %0,1" "\n\t" // 2 cycles                                       
        "brne 1b" : "=w" (us) : "0" (us) // 2 cycles                            
    );                                                                          
    // return = 4 cycles                                                        
```

I don't speak that dialect of assembler myself, but you can see from the comments the idea is very similar.

You could wrap it in a function and do a function call:

```
// delay expressed in units of ~6 microseconds
void sleep(int n) {
  for (int i = 0; i < n; i++) { for (char j = 0; j < 255; j++); }
}
```

and use it like this:

```
sleep(20);
```

In this firmware there was probably little benefit to splititng that code out into a separate function.



</blockquote></details>

Nice explanation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/38)*

**Comment by dtkaczyk** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/38)*

**Comment by dtkaczyk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[usb/hantek6022be/custom_firmware/device.c, line 130 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/38#-KplA9J98Xz7GrJuS9Lk:-Kq7Ybo1AAVfcOztaJiP:b32w0x) ([raw file](https://github.com/zagrodzki/goscope/blob/403d614b27e5907775f75908226e1a57e83c6344/usb/hantek6022be/custom_firmware/device.c#L130)):*
<details><summary><i>Previously, dtkaczyk (Dominika Tkaczyk) wrote…</i></summary><blockquote>

Nice explanation.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/38)*

**Pull request merged**
