### PR TITLE
interpolation, take #1

### PR DESCRIPTION
**Pull request by dtkaczyk**
This change is [Reviewable](https://reviewable.io/reviews/zagrodzki/goscope/21)

### CODE REVIEW

**Comment by zagrodzki** [comment]
Reviewed 10 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_[gui/gui.go, line 18 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVz9cJvuXyqnERrfnSb:-KVz9cJvuXyqnERrfnSc:bfzmmd1) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/gui.go#L18)):_

> ``` Go
> 
> import (
>   "github.com/zagrodzki/goscope/scope"
> ```

this was actually fine, separating go std library imports from non-std imports makes sense.

---

_[gui/gui.go, line 178 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzAWg-j9vcyv3Lvdok:-KVzAWg-j9vcyv3Lvdol:be07mjh) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/gui.go#L178)):_

> ``` Go
> // DrawSamples draws samples in the image rectangle defined by
> // starting (upper left) and ending (lower right) pixel.
> func (plot Plot) DrawSamples(samples []scope.Sample, interp interpMethod, tracePos TracePos, start, end image.Point, col color.RGBA) error {
> ```

perhaps make interpMethod part of the tracePos (then it could be renamed traceParams). I think that we might be reaching the point where the signature gets too long.
We might also collate start and end into a single image.Rectangle.

---

_[gui/gui_test.go, line 170 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzCjHylgtYC2x7l2Cj:-KVzCjHzx-NTubMuzanq:b-5jogxh) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/gui_test.go#L170)):_

> ``` Go
>           minPointCount: 1000,
>           refPlotFile:   "lines-gp.png",
>       },
> ```

a frequently seen test case for sinc interpolation is impulse response (f = 1 on the middle sample, 0 otherwise) and step response (f = 0 for the first half, 1 for the second half of the time). Perhaps you could add these as well? I expect the results to look similar to this: http://zagrodzki.net/~sebek/figure_1.svg and http://zagrodzki.net/~sebek/figure_2.svg

---

_[gui/interpolation.go, line 24 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVz8jJ1d8kuHwFFTGgh:-KVz8jJ1d8kuHwFFTGgi:b-v62wjc) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/interpolation.go#L24)):_

> ``` Go
> )
> 
> type interpMethod interface {
> ```

go convention would be "interpolator".

You could also use a function rather than interface:

type interpolator func([]scope.Sample, int) ([]scope.Sample, error)

---

_[gui/interpolation.go, line 28 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzB4KiwpWL6k6UKfbD:-KVzB4KiwpWL6k6UKfbE:b-bjxcfh) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/interpolation.go#L28)):_

> ``` Go
> }
> 
> type constInterpolation struct{}
> ```

stepInterpolation

---

_[gui/interpolation.go, line 55 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzB8De5IIUFrrUFD7j:-KVzB8De5IIUFrrUFD7k:b-58iu91) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/interpolation.go#L55)):_

> ``` Go
> }
> 
> type linearInterpolation struct {
> ```

closing brace on the same line

---

_[gui/interpolation.go, line 86 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzBkoRrMz6s5Yh6sl6:-KVzBkoRrMz6s5Yh6sl7:b-2or7gt) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/interpolation.go#L86)):_

> ``` Go
> }
> 
> type sincInterpolation struct {
> ```

one line

---

_[gui/interpolation.go, line 126 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzBR9Ea_4aeK7CoG-V:-KVzBR9Ea_4aeK7CoG-W:b45gpw4) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/interpolation.go#L126)):_

> ``` Go
> }
> 
> func constFunction(size int, value scope.Sample) []scope.Sample {
> ```

maybe constValue?

---

_[gui/interpolation.go, line 89 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzJ1abrlW0bcH2cU7y:-KVzJ1ackDBBRaTrCVSy:b-y3khbn) ([raw file](https://github.com/zagrodzki/goscope/blob/dfab2b061f09b565de90de9110740cfd610702b2/gui/interpolation.go#L89)):_

> ``` Go
> }
> 
> func (interp sincInterpolation) interpolate(samples []scope.Sample, size int) ([]scope.Sample, error) {
> ```

can you add benchmarks as well? I'd like to know how much it costs to run the full FFT/IFFT. In particular, should we zero-pad the signal to the nearest power-of-2 to use the more efficient FFT implementation?
A quick bench for radix (power of 2) vs bluestein (non-power of 2) shows 10x CPU overhead.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/21)_

**Comment by dtkaczyk** [comment]
Review status: 4 of 13 files reviewed at latest revision, 9 unresolved discussions.

---

_[gui/gui.go, line 18 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVz9cJvuXyqnERrfnSb:-KWXC2lt7yX49YB9Z9bD:b-m6utdq) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/gui.go#L18)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> this was actually fine, separating go std library imports from non-std imports makes sense.
> </details>
> Done. Not really sure how and when this was changed.

---

_[gui/gui.go, line 178 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzAWg-j9vcyv3Lvdok:-KWXCMsgSSPSSLnJPCsa:bx4nh62) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/gui.go#L178)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> perhaps make interpMethod part of the tracePos (then it could be renamed traceParams). I think that we might be reaching the point where the signature gets too long.
> We might also collate start and end into a single image.Rectangle.
> </details>
> Done and done.

---

_[gui/gui_test.go, line 170 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzCjHylgtYC2x7l2Cj:-KWXChl8fpZ7kJ6io6xK:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/gui_test.go#L170)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> a frequently seen test case for sinc interpolation is impulse response (f = 1 on the middle sample, 0 otherwise) and step response (f = 0 for the first half, 1 for the second half of the time). Perhaps you could add these as well? I expect the results to look similar to this: http://zagrodzki.net/~sebek/figure_1.svg and http://zagrodzki.net/~sebek/figure_2.svg
> </details>
> Done.

---

_[gui/interpolation.go, line 24 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVz8jJ1d8kuHwFFTGgh:-KWXClLFc0HS7mQEOZ3l:bx4nh62) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/interpolation.go#L24)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> go convention would be "interpolator".
> 
> You could also use a function rather than interface:
> 
> type interpolator func([]scope.Sample, int) ([]scope.Sample, error)
> 
> </details>
> Done and done.

---

_[gui/interpolation.go, line 28 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzB4KiwpWL6k6UKfbD:-KWXCngrnDjfnDdBg6ZH:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/interpolation.go#L28)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> stepInterpolation
> </details>
> Done.

---

_[gui/interpolation.go, line 55 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzB8De5IIUFrrUFD7j:-KWXCp5ttuL051LGjCLn:b-7nte2i) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/interpolation.go#L55)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> closing brace on the same line
> </details>
> Not needed anymore.

---

_[gui/interpolation.go, line 86 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzBkoRrMz6s5Yh6sl6:-KWXD-AdBg40FmSomS7U:b-7nte2i) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/interpolation.go#L86)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> one line
> </details>
> Not needed anymore.

---

_[gui/interpolation.go, line 126 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzBR9Ea_4aeK7CoG-V:-KWXD9jYLcd3LQwBDGeP:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/f3e2f073686b43c6e1dd65224dbb08647576e0fd/gui/interpolation.go#L126)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> maybe constValue?
> </details>
> Done.

---

_[gui/interpolation.go, line 89 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KVzJ1abrlW0bcH2cU7y:-KWXD89h1pUU-DS4Fh-c:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/dfab2b061f09b565de90de9110740cfd610702b2/gui/interpolation.go#L89)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> can you add benchmarks as well? I'd like to know how much it costs to run the full FFT/IFFT. In particular, should we zero-pad the signal to the nearest power-of-2 to use the more efficient FFT implementation?
> A quick bench for radix (power of 2) vs bluestein (non-power of 2) shows 10x CPU overhead.
> 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/21)_

**Comment by zagrodzki** [comment]
Reviewed 9 of 10 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[gui/interpolation.go, line 118 at r3](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KWc7_czsNoCzj7Gs0ga:-KWc7_d-iGUMNRSLlzuq:bcuk57a) ([raw file](https://github.com/zagrodzki/goscope/blob/5cef9c5d5e22d98175f19d4227032ea9b43972f4/gui/interpolation.go#L118)):_

> ``` Go
> // zeros to the input samples to make sure their number is a power of 2
> func SincZeroPadInterpolator(samples []scope.Sample, size int) ([]scope.Sample, error) {
>   logLenSamples := int(math.Log2(float64(len(samples))))
> ```

the math cost might be high enough that it might be cheaper to start with 64 samples and keep shifting the size to the left by one bit until it's greater equal to num samples. And padding to 64 samples if the sample size is much smaller is still fine, and the difference in cost between, say, 8 and 64 samples won't make much difference.

So perhaps something like:
padLen := 64
for padLen < size {
 padLen = padLen << 1
}
would work well and avoid slow floating point math.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/21)_

**Comment by zagrodzki** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[gui/interpolation.go, line 118 at r3](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KWc7_czsNoCzj7Gs0ga:-KWcC26341X4woKng5v_:b-ryo2gn) ([raw file](https://github.com/zagrodzki/goscope/blob/5cef9c5d5e22d98175f19d4227032ea9b43972f4/gui/interpolation.go#L118)):_

> padLen := 64
> for padLen < size {
>  padLen = padLen << 1
> }

Yeah, a simple benchmark shows for 2^16-3 samples:
BenchmarkLen/math_65533-4           20000000           101 ns/op
BenchmarkLen/shift_65533-4          300000000            5.82 ns/op

Log takes the same time regardless of the input size, for larger lengths shift is slower.

There's yet another implementation, with "find the most significant non-zero bit":

mask := 2<<31  // mask is always a power of 2
for mask > 0 {
  if mask & size != 0 {
    if mask == size {
      padLen = mask
    } else {
      padLen = mask << 1
    }
    break
  }
}

and it's even slightly faster, because it uses only the bitwise operations and "non zero" comparison op:

BenchmarkLen/math_32765-4           20000000            99.2 ns/op
BenchmarkLen/shift_32765-4          200000000            6.29 ns/op
BenchmarkLen/first_32765-4          2000000000           1.44 ns/op

BenchmarkLen/math_65533-4           20000000           111 ns/op
BenchmarkLen/shift_65533-4          200000000            6.87 ns/op
BenchmarkLen/first_65533-4          2000000000           1.39 ns/op

BenchmarkLen/math_131069-4          20000000           112 ns/op
BenchmarkLen/shift_131069-4         200000000            7.35 ns/op
BenchmarkLen/first_131069-4         2000000000           1.36 ns/op

But I think it's less readable at the same time, so I'm fine with simple int shifting.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/21)_

**Comment by zagrodzki** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

_[gui/interpolation.go, line 120 at r4](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KWsquuEGy-gs23Y89Hq:-KWsquuEGy-gs23Y89Hr:b46rwrq) ([raw file](https://github.com/zagrodzki/goscope/blob/b57ec1a26ccec274f981c7ab5ada792b6e9d29f8/gui/interpolation.go#L120)):_

> ``` Go
>   samplesLen := len(samples)
>   padSamplesLen := samplesLen
>   mask := 1 << (8*unsafe.Sizeof(1) - 2)
> ```

perhaps we could just assume we're not going to have more than 2^30 samples (it wouldn't work very well in either case), and use 2^30 for both 32bit and 64bit int.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/21)_

**Comment by zagrodzki** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

_[gui/interpolation.go, line 120 at r4](https://reviewable.io:443/reviews/zagrodzki/goscope/21#-KWsquuEGy-gs23Y89Hq:-KWsrKsxmWmkHQaVcbz-:bd9vlo7) ([raw file](https://github.com/zagrodzki/goscope/blob/b57ec1a26ccec274f981c7ab5ada792b6e9d29f8/gui/interpolation.go#L120)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> perhaps we could just assume we're not going to have more than 2^30 samples (it wouldn't work very well in either case), and use 2^30 for both 32bit and 64bit int.
> </details>
> or even 2^20 or something, plotting more than 1M samples on a screen that has small few k pixels horizontal resolution at most is not going to work well in any case.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/21)_

**Comment by zagrodzki** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/21)_

**Comment by zagrodzki** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/21)_

**Pull request merged**
