### PR TITLE
tests comparing generated plot to gnuplot version

### PR DESCRIPTION
**Pull request by dtkaczyk**
This change is [Reviewable](https://reviewable.io/reviews/zagrodzki/goscope/20)

### CODE REVIEW

**Comment by zagrodzki** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[gui/gui_test.go, line 34 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQdlLT0VkZ9Rm9jiZq:-KUQdlLUZ1zO84M6AzbN:bjh6zbs) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L34)):_

> ``` Go
> // TODO: tests comparing the resulting plot image to the perfect image
> 
> // isOn checks whether a pixel is a part of the plot or the background,
> ```

perhaps "isOn returns true if pixel x,y is of a different color than white."

---

_[gui/gui_test.go, line 40 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQarlpILscns5v_v_m:-KUQarlpILscns5v_v_n:b-9122tx) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L40)):_

> ``` Go
> }
> 
> // evalSim calculates the similarity between two plots: "true" plot
> ```

A common designation is "golden" for the known-good result.

---

_[gui/gui_test.go, line 44 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQceTFU5tL8wYS3f01:-KUQceTFU5tL8wYS3f02:b-liqcvi) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L44)):_

> ``` Go
> // the similarity is the fraction of the test plot that also
> // belongs to the true plot
> func evalSim(truePlot, testPlot image.Image) (int, float64) {
> ```

would it make sense to also check that you have a pixel in every column of the plot?

---

_[gui/gui_test.go, line 61 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQhfUEnw1RKN41hbvD:-KUQhfUEnw1RKN41hbvE:b-8hfc2x) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L61)):_

> ``` Go
>       }
>   }
>   return all, float64(matched) / float64(all)
> ```

would you actually expect any points outside of the golden plot? Would it not be better to expect that the golden will be wide enough to already include any error margin you want to include? 

---

_[gui/gui_test.go, line 67 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQd1NfT533iKf5qeKp:-KUQd1NfT533iKf5qeKq:bk4pfj7) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L67)):_

> ``` Go
> // minPointCount is the minimum number of pixels of the tested plot.
> // minSimilarity is the minimum similarity of the plots.
> func testPlot(t *testing.T, plotFile string, samples []scope.Sample, minPointCount int, minSimilarity float64) {
> ```

it's considered a bad practice to leak testing.T outside of tests. Helper functions should behave like other functions, and return an error. The test function can then decide to error/fatal with a useful error message.

I think this will no longer be a problem once you use a table driven test, see below first.

---

_[gui/gui_test.go, line 95 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQfNDsln2_2P1oI68M:-KUQfNDt6Xv_v8UOfgmI:b-yxirxx) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L95)):_

> ``` Go
> }
> 
> func TestSin(t *testing.T) {
> ```

this looks like a good material for a table driven test - you test the same underlying function with different inputs/outputs, but the overall mechanism of the test is identical.

func TestPlotting(t *testing.T) {
for _, tc := range []struct{
   desc string
   num int
   gen func(int) scope.Sample
   golden string
}{
{
  desc: "2 periods of a sinusoid",
  num: 1000,
  gen: func(i int) scope.Sample {
    return scope.Sample(math.Sin(float64(i)) \* 4 \* math.Pi /999)
  },
  golden: "sin-gp.png",
 },
 ...
}{
  samples := make(...)
  for i := 0; i < tc.num; i++ {
    samples[i] = tc.gen(i)
  }
  ... the body of testPlot goes here ...
}

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/20)_

**Comment by zagrodzki** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[gui/gui_test.go, line 32 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQiEMya3spzAOG1v_E:-KUQiEMya3spzAOG1v_F:b-mugp3j) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L32)):_

> ``` Go
> 
> // TODO: more tests for specific functions
> // TODO: tests comparing the resulting plot image to the perfect image
> ```

remove this TODO

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/20)_

**Comment by dtkaczyk** [comment]
Review status: 6 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

_[gui/gui_test.go, line 32 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQiEMya3spzAOG1v_E:-KUmG1P82pMZOElyoQ91:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L32)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> remove this TODO
> </details>
> Done.

---

_[gui/gui_test.go, line 34 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQdlLT0VkZ9Rm9jiZq:-KUmG5nazcPFAkjpxLKn:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L34)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> perhaps "isOn returns true if pixel x,y is of a different color than white."
> </details>
> Done.

---

_[gui/gui_test.go, line 40 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQarlpILscns5v_v_m:-KUmG8W7lOylMRE3Ifyb:bu618fe) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L40)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> A common designation is "golden" for the known-good result.
> </details>
> Change into "reference".

---

_[gui/gui_test.go, line 44 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQceTFU5tL8wYS3f01:-KUmGKpcdDv2zPCV2Dnw:bqmjwcz) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L44)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> would it make sense to also check that you have a pixel in every column of the plot?
> </details>
> Added.

---

_[gui/gui_test.go, line 61 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQhfUEnw1RKN41hbvD:-KUmH9KT5NhI4lzcW3Sf:b-17q4fl) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L61)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> would you actually expect any points outside of the golden plot? Would it not be better to expect that the golden will be wide enough to already include any error margin you want to include? 
> </details>
> Rewritten.

---

_[gui/gui_test.go, line 67 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQd1NfT533iKf5qeKp:-KUmHDMWr9kMWU_FTwJj:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L67)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> it's considered a bad practice to leak testing.T outside of tests. Helper functions should behave like other functions, and return an error. The test function can then decide to error/fatal with a useful error message.
> 
> I think this will no longer be a problem once you use a table driven test, see below first.
> </details>
> Done.

---

_[gui/gui_test.go, line 95 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQfNDsln2_2P1oI68M:-KUmHF7__uuK-6g5IW8N:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L95)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> this looks like a good material for a table driven test - you test the same underlying function with different inputs/outputs, but the overall mechanism of the test is identical.
> 
> func TestPlotting(t *testing.T) {
> for _, tc := range []struct{
>    desc string
>    num int
>    gen func(int) scope.Sample
>    golden string
> }{
> {
>   desc: "2 periods of a sinusoid",
>   num: 1000,
>   gen: func(i int) scope.Sample {
>     return scope.Sample(math.Sin(float64(i)) \* 4 \* math.Pi /999)
>   },
>   golden: "sin-gp.png",
>  },
>  ...
> }{
>   samples := make(...)
>   for i := 0; i < tc.num; i++ {
>     samples[i] = tc.gen(i)
>   }
>   ... the body of testPlot goes here ...
> }
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/20)_

**Comment by zagrodzki** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

_[gui/gui_test.go, line 40 at r1](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUQarlpILscns5v_v_m:-KUmGNBGkEbyLSOsJCpz:b-u1k1lu) ([raw file](https://github.com/zagrodzki/goscope/blob/a5716449e7bd9c5e0d870709037b08e6670c9f1a/gui/gui_test.go#L40)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> A common designation is "golden" for the known-good result.
> </details>
> Apparenfly not so common. settled on "reference".

---

_[gui/gui_test.go, line 44 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmHVTNQ0bkExfV6Wgc:-KUmHVTNQ0bkExfV6Wgd:ba0n3ss) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L44)):_

> ``` Go
> // 3) contains at least one pixel in every column
> // 4) contains at least minPointCount pixels
> func evaluatePlot(refPlot, testPlot image.Image, minPointCount int) (bool, string) {
> ```

The only time you return true is when string is empty. Perhaps just return an error type, and check for nil error in the caller.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/20)_

**Comment by zagrodzki** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[gui/gui_test.go, line 54 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmIxhvyjj1OmgYEQcl:-KUmIxhxqIbNUzAu3vT4:bt0dh3v) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L54)):_

> ``` Go
>       for y := b.Min.Y; y < b.Max.Y; y++ {
>           testOn := isOn(testPlot, x, y)
>           col = col || testOn
> ```

Nitpick: this is clever, but probably less readable than "col = true" in the "if testOn" block below.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/20)_

**Comment by zagrodzki** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[gui/gui_test.go, line 45 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmJcdKAq-MAfK38jN5:-KUmJcdNJmmN11aVj7aP:b-my0qpl) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L45)):_

> ``` Go
> // 4) contains at least minPointCount pixels
> func evaluatePlot(refPlot, testPlot image.Image, minPointCount int) (bool, string) {
>   if refPlot.Bounds() != testPlot.Bounds() {
> ```

Idiomaric:

if got, want := refplot.Bounds(), testPlot.Bounds(); got != want ... ("Got %, want %v", got, want)

---

_[gui/gui_test.go, line 59 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmK56gkrR5erpokNMJ:-KUmK56gkrR5erpokNMK:bsp8lu7) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L59)):_

> ``` Go
>           }
>           if testOn && !isOn(refPlot, x, y) {
>               return false, "test plot is not contained in reference plot"
> ```

More helpful message: point %v of the plot is not marked on the reference plot

The idea is: the user needs to have enough information in the test error message to be able to find the bug and fix it without looking at the test code.

---

_[gui/gui_test.go, line 66 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmKfUOfaTA1qPG8RcW:-KUmKfUOfaTA1qPG8RcX:bpodwdn) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L66)):_

> ``` Go
>       }
>   }
>   if pointCount < minPointCount {
> ```

Ditto, got/want, to  avoid mixing up names later.

---

_[gui/gui_test.go, line 124 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmKrJZXzbKteIDHTFz:-KUmKrJ_BYvXygTD1TEI:b59g3bn) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L124)):_

> ``` Go
>       file, err := os.Open(tc.refPlotFile)
>       if err != nil {
>           t.Fatalf("Cannot open file: %v", err)
> ```

Which file?

Also, with a table driven test, t.Errorf + continue will work better than Fatalf.

---

_[gui/gui_test.go, line 128 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmKvkgKZRQejnSCD_5:-KUmKvkgKZRQejnSCD_6:b-jzp4x4) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L128)):_

> ``` Go
>       refPlot, err := png.Decode(file)
>       if err != nil {
>           t.Fatalf("Cannot decode file: %v", err)
> ```

Ditto, which file

---

_[gui/gui_test.go, line 137 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmLGBO-eNmOjcfv7cD:-KUmLGBPrhXOJ8jeH6Bt:b-3xomkq) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L137)):_

> ``` Go
>       eval, msg := evaluatePlot(refPlot, testPlot, tc.minPointCount)
>       if !eval {
>           t.Errorf(fmt.Sprintf("error in evaluating plot %v: %v", tc.desc, msg))
> ```

Mention the name of the ref file

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/20)_

**Comment by dtkaczyk** [comment]
Review status: 6 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

_[gui/gui_test.go, line 44 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmHVTNQ0bkExfV6Wgc:-KUmm6WCtqcPvcQdCA6U:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L44)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> The only time you return true is when string is empty. Perhaps just return an error type, and check for nil error in the caller.
> </details>
> Done.

---

_[gui/gui_test.go, line 45 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmJcdKAq-MAfK38jN5:-KUmmJecifdCcESnTOwI:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L45)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> Idiomaric:
> 
> if got, want := refplot.Bounds(), testPlot.Bounds(); got != want ... ("Got %, want %v", got, want)
> </details>
> Done.

---

_[gui/gui_test.go, line 54 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmIxhvyjj1OmgYEQcl:-KUmmO7p3U4hhSK8mS47:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L54)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> Nitpick: this is clever, but probably less readable than "col = true" in the "if testOn" block below.
> </details>
> Done.

---

_[gui/gui_test.go, line 59 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmK56gkrR5erpokNMJ:-KUmmSNIY_qeYbMNqfXm:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L59)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> More helpful message: point %v of the plot is not marked on the reference plot
> 
> The idea is: the user needs to have enough information in the test error message to be able to find the bug and fix it without looking at the test code.
> </details>
> Done.

---

_[gui/gui_test.go, line 66 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmKfUOfaTA1qPG8RcW:-KUmmXwm07sPgRVA9qO3:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L66)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> Ditto, got/want, to  avoid mixing up names later.
> </details>
> Done.

---

_[gui/gui_test.go, line 124 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmKrJZXzbKteIDHTFz:-KUmmgQbpepbuqdzVk3-:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L124)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> Which file?
> 
> Also, with a table driven test, t.Errorf + continue will work better than Fatalf.
> </details>
> Done.

---

_[gui/gui_test.go, line 128 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmKvkgKZRQejnSCD_5:-KUmmhglA_bwJ46mdbV1:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L128)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> Ditto, which file
> </details>
> Done.

---

_[gui/gui_test.go, line 137 at r2](https://reviewable.io:443/reviews/zagrodzki/goscope/20#-KUmLGBO-eNmOjcfv7cD:-KUmmlKN0737u7UrJoH7:b-896fix) ([raw file](https://github.com/zagrodzki/goscope/blob/61b44e44d0b5b578d4437c2dc8926d91eb6a3005/gui/gui_test.go#L137)):_
<details><summary>

<i>Previously, zagrodzki wrote…</i></summary>



> Mention the name of the ref file
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/20)_

**Comment by zagrodzki** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zagrodzki/goscope/20)_

**Pull request merged**
